#!/usr/bin/env bash

venvman_command_help_tag() {
    COMMAND=$1
    shift
    
    OPTIONS=""
    OPTIONS_LENS=""
    OPTIONS_MAX_LEN=0
    OPTIONS_DESCRIPTIONS=""
    
    EXAMPLES=""
    EXAMPLES_LENS=""
    EXAMPLES_MAX_LEN=0
    EXAMPLES_DESCRIPTIONS=""
    
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --options)
                shift
                while [ "$#" -gt 0 ] && [ "${1}" != "--option-descriptions" ]; do
                    OPTIONS="${OPTIONS}\n  $1"
                    len=$(echo "$1" | wc -c)
                    OPTIONS_LENS="${OPTIONS_LENS} $len"
                    if [ $len -ge $OPTIONS_MAX_LEN ]; then
                        OPTIONS_MAX_LEN="$len"
                    fi
                    shift
                done
                ;;
            --option-descriptions)
                shift
                i=1
                while [ "$#" -gt 0 ] && [ "${1}" != "--examples" ]; do
                    len=$(echo "$OPTIONS_LENS" | awk -v i="$i" '{print $i}')
                    delta=$(( $OPTIONS_MAX_LEN - $len ))
                    spaces=$(printf '%*s' "$delta" '')
                    OPTIONS_DESCRIPTIONS="${OPTIONS_DESCRIPTIONS}\n$spaces : $1"
                    i=$((i + 1))
                    shift
                done
                ;;
            --examples)
                shift
                while [ "$#" -gt 0 ] && [ "${1}" != "--example-descriptions" ]; do
                    EXAMPLES="${EXAMPLES}\n  $1"
                    len=$(echo "$1" | wc -c)
                    EXAMPLES_LENS="${EXAMPLES_LENS} $len"
                    if [ "$len" -ge $EXAMPLES_MAX_LEN ]; then
                        EXAMPLES_MAX_LEN="$len"
                    fi
                    shift
                done
                ;;
            --example-descriptions)
                shift
                i=1
                while [ "$#" -gt 0 ] && [ "${1#--}" = "$1" ]; do
                    len=$(echo "$EXAMPLES_LENS" | awk -v i="$i" '{print $i}')
                    delta=$(( $EXAMPLES_MAX_LEN - $len ))
                    spaces=$(printf '%*s' "$delta" '')
                    EXAMPLES_DESCRIPTIONS="${EXAMPLES_DESCRIPTIONS}\n$spaces : $1"
                    i=$((i + 1))
                    shift
                done
                ;;
            *)
                return 1
                ;;
        esac
    done
    
    # Print the help message
    echo "Usage:"
    echo "  venvman $COMMAND [options]"
    echo
    echo "Options:"
    paste -d ' ' <(echo -e "$OPTIONS") <(echo -e "$OPTIONS_DESCRIPTIONS")
    echo
    echo "Examples:"
    paste -d ' ' <(echo -e "$EXAMPLES") <(echo -e "$EXAMPLES_DESCRIPTIONS")
}

venvman_command_help_tag $@

    
unset \
    OPTIONS OPTIONS_LENS OPTIONS_MAX_LEN OPTIONS_DESCRIPTIONS \
    EXAMPLES EXAMPLES_LENS EXAMPLES_MAX_LEN EXAMPLES_DESCRIPTIONS \
    len delta spaces i
