#!/usr/bin/env bash

venvman_help_tag() {
    COMMANDS=""
    COMMANDS_LENS=""
    COMMANDS_MAX_LEN=0
    COMMANDS_DESCRIPTIONS=""
    
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --commands)
                shift
                while [ "$#" -gt 0 ] && [ "${1}" != "--commands-descriptions" ]; do
                    COMMANDS="${COMMANDS}\n  $1"
                    len=$(echo "$1" | wc -c)
                    COMMANDS_LENS="${COMMANDS_LENS} $len"
                    if [ $len -ge $COMMANDS_MAX_LEN ]; then
                        COMMANDS_MAX_LEN="$len"
                    fi
                    shift
                done
                ;;
            --commands-descriptions)
                shift
                i=1
                while [ "$#" -gt 0 ] && [ "${1}" != "--examples" ]; do
                    len=$(echo "$COMMANDS_LENS" | awk -v i="$i" '{print $i}')
                    delta=$(( $COMMANDS_MAX_LEN - $len ))
                    spaces=$(printf '%*s' "$delta" '')
                    COMMANDS_DESCRIPTIONS="${COMMANDS_DESCRIPTIONS}\n$spaces : $1"
                    i=$((i + 1))
                    shift
                done
                ;;
            *)
                return 1
                ;;
        esac
    done
    
    # Print the help message
    echo "Commands:"
    paste -d ' ' <(echo -e "$COMMANDS") <(echo -e "$COMMANDS_DESCRIPTIONS")
    echo
    echo "Usage:"
    echo "  See \`venvman <command> --help\` for usage of each command."
}

venvman_help_tag $@


unset \
    COMMANDS COMMANDS_DESCRIPTIONS COMMANDS_LENS COMMANDS_MAX_LEN \
    i len delta spaces
