#!/usr/bin/env bash

version_is_branch() {
    VERSION=$1
    for x in $(git ls-remote --heads "${VENVMAN_CPYTHON_REMOTE_URL}"); do
        line=$(echo $x | grep "refs/heads/${VERSION}")
        if [ -z $line ]; then
            return 1
        fi
        if [ "$line" = "refs/heads/${VERSION}" ]; then
            return 0
        fi
    done
    return 1
}

version_is_branch "$1"
