#!/usr/bin/env bash


get_python_bin_path() {
    ${VENVMAN_UTILS_DIR}/get_python_bin_path $1
}


version_is_branch() {
    ${VENVMAN_UTILS_DIR}/cpython-github/version_is_branch $@
}


get_tag_from_version() {
    ${VENVMAN_UTILS_DIR}/cpython-github/get_tag_from_version $@
}


verify_cpython_repo() {
    ${VENVMAN_UTILS_DIR}/cpython-github/verify_cpython_repo
}


build_python_version_from_source() {
    VERSION="$1"

    case "$2" in
        --local)
            case "$3" in
                "true")
                    LOCAL=$3
                    shift 2
                    ;;
                "false")
                    LOCAL=$3
                    shift 2
                    ;;
                *)
                    echo "ERROR: build_python_version_from_source --local must be true or false"
                    return 1
                    ;;
            esac
            ;;

        --skip-tests)
            case "$3" in
                "true")
                    SKIP_TESTS=$3
                    shift 2
                    ;;
                "false")
                    SKIP_TESTS=$3
                    shift 2
                    ;;
                *)
                    echo "ERROR: build_python_version_from_source --skip-tests must be true or false"
                    return 1
                    ;;
            esac
            ;;

        *)
            if [ -n "$2" ]; then
                echo "ERROR build_python_version_from_source: invalid input $2" >&2
                return 1
            fi
            ;;
    esac

    if [ -z $LOCAL ]; then
        echo "ERROR: build_python_version_from_source --local is missing" >&2
        return 1
    fi
    
    if BIN_PATH=$(get_python_bin_path $VERSION); then
        echo "python${VERSION} already exists at ${BIN_PATH}"
        return 0
    fi
    
    verify_cpython_repo || return 1

    MY_PWD="$(pwd)"
    cd $VENVMAN_CPYTHON_REPO_DIR || return 1


    VERSION_PARTS=$(echo "${VERSION}" | tr '.' ' ')
    NUM_PARTS=$(echo "$(echo "${VERSION_PARTS}" | wc -w)" | xargs)

    if [ "${#NUM_PARTS}" -ne "1" ]; then
        echo "ERROR: NUM_PARTS has len longer than 1" >&2
        return 1
    fi

    git fetch --all --tags

    if [ "$NUM_PARTS" = 2 ]; then
        if version_is_branch "$VERSION" --local $LOCAL; then
            BRANCH=$VERSION
        fi

    elif [ "$NUM_PARTS" != 3 ]; then
        return 1
    fi

    TAG=$(get_tag_from_version "$VERSION" --local $LOCAL) || return 1

    CHECKOUT=$([ -n "$BRANCH" ] && echo "$BRANCH" || echo $TAG)

    echo 
    echo "Python $VERSION is available at ${VENVMAN_CPYTHON_REMOTE_URL} with 'git checkout ${CHECKOUT}'."
    if [ -n "${BRANCH}" ]; then
        echo "The version available at the ${VERSION} branch is ${TAG}"
    fi
    printf "We can install this version and the resulting installation "
    printf "would be located at ${VENVMAN_PYTHON_BUILDS_DIR}/${VERSION}\n"
    echo
    echo "To do this, we would run following:"
    echo
    echo "\$ cd ${VENVMAN_CPYTHON_REPO_DIR}" 
    echo "\$"
    echo "\$ if [ \$(git remote get-url origin) != ${VENVMAN_CPYTHON_REMOTE_URL} ]; then"
    echo "\$     return 1"
    echo "\$ fi"
    echo "\$"
    echo "\$ git checkout "$CHECKOUT""
    echo "\$ git reset --hard "$CHECKOUT""
    echo "\$"
    echo "\$ ./configure --prefix="${VENVMAN_PYTHON_BUILDS_DIR}/${VERSION}""
    echo "\$ make"
    echo "\$ make test"
    echo "\$ make install"
    echo
    printf "Would you like to continue with the install now? [Y/n]: "
    read -r response
    case "$response" in
        Y|y)
            ;;
        *)
            echo "Exiting the install."
            cd $MY_PWD
            return 1
            ;;
    esac
    
    git checkout "$CHECKOUT" || return 1
    git reset --hard "$CHECKOUT" || return 1

    if [ ! -f "./configure" ]; then
        echo "ERROR: ./configure is missing" >&2
        return 1
    fi

    if [ ! -f "./Makefile.pre.in" ]; then
        echo "ERROR: Makefile.pre.in is missing" >&2
        return 1
    fi

    if [ -f "./Makefile.pre" ]; then
        echo "Removing old Makefile.pre"
        rm ./Makefile.pre
    fi

    if [ -f "./Makefile" ]; then
        echo "Removing old Makefile"
        rm ./Makefile
    fi
 
    ./configure --prefix="${VENVMAN_PYTHON_BUILDS_DIR}/${VERSION}" || return 1
    if [ $(command -v nproc &> /dev/null) ]; then
        make -j$(nproc) || cd $MY_PWD && return 1
    elif [ $(command -v sysctl &> /dev/null) ]; then
        ncpu=$(sysctl -n hw.ncpu)
        if [ -n "$ncpu" ]; then
            make -j${ncpu} || cd $MY_PWD && return 1
        fi
    else
        make || cd $MY_PWD return 1
    fi
    
    if [ "$SKIP_TESTS" = "false" ]; then
        make test
    fi

    if ! make install; then
        echo "ERROR: make install failed" >&2
        echo "It is suggested to run"
        echo "    rm -rf ${VENVMAN_CPYTHON_REPO_DIR}"
        echo "    git clone ${VENVMAN_CPYTHON_REMOTE_URL} ${VENVMAN_CPYTHON_REPO_DIR}"
        echo "Then rerun the venvman make command."
        return 1
    fi

    cd $MY_PWD
    unset MY_PWD

    if [ "$?" -gt 0 ]; then
        echo "'make install' failed" >&2
        return 1
    fi

    if ! get_python_bin_path $VERSION > /dev/null; then
        echo "'make install' was successfull but the resulting binary for python ${VERSION} could not be found." >&2
        return 1
    fi
}


build_python_version_from_source "$@"
