#!/usr/bin/env bash


get_python_bin_path() {
    ${VENVMAN_UTILS_DIR}/get_python_bin_path $1
}


verify_cpython_repo() {
    ${VENVMAN_UTILS_DIR}/cpython-github/verify_cpython_repo
}


get_git_checkout_for_version() {
    ${VENVMAN_UTILS_DIR}/cpython-github/get_git_checkout_for_version $@
}


build_python_version_from_source() {
    VERSION="$1"

    case "$2" in
        --local)
            case "$3" in
                "true")
                    LOCAL=$3
                    shift 2
                    ;;
                "false")
                    LOCAL=$3
                    shift 2
                    ;;
                *)
                    echo "ERROR: build_python_version_from_source --local must be true or false" >&2
                    return 1
                    ;;
            esac
            ;;

        --skip-tests)
            case "$3" in
                "true")
                    SKIP_TESTS=$3
                    shift 2
                    ;;
                "false")
                    SKIP_TESTS=$3
                    shift 2
                    ;;
                *)
                    echo "ERROR: build_python_version_from_source --skip-tests must be true or false" >&2
                    return 1
                    ;;
            esac
            ;;

        *)
            if [ -n "$2" ]; then
                echo "ERROR build_python_version_from_source: invalid input $2" >&2
                return 1
            fi
            ;;
    esac

    if [ -z $LOCAL ]; then
        echo "ERROR: build_python_version_from_source --local is missing" >&2
        return 1
    fi
    
    if BIN_PATH=$(get_python_bin_path $VERSION); then
        echo "python${VERSION} already exists at ${BIN_PATH}"
        return 0
    fi
    
    verify_cpython_repo || return 1

    OUT=$(get_git_checkout_for_version $VERSION)
    CHECKOUT=$(echo $OUT | awk "{print \$1}")
    TAG=$(echo $OUT | awk "{print \$2}")

    MY_PWD="$(pwd)"
    cd $VENVMAN_CPYTHON_REPO_DIR || return 1

    echo "--------------------------------------------------"
    echo "Checking out $CHECKOUT"
    echo "--------------------------------------------------"
    git checkout "$CHECKOUT" || return 1
    git reset --hard "$CHECKOUT" || return 1

    if [ -f "./Makefile.pre" ]; then
        rm ./Makefile.pre
    fi

    if [ -f "./Makefile" ]; then
        rm ./Makefile
    fi

    echo "--------------------------------------------------"
    echo "Python $VERSION is available at ${VENVMAN_CPYTHON_REMOTE_URL} with 'git checkout ${CHECKOUT}'."
    if [[ ! "$CHECKOUT" == *"v"* ]] ; then
        echo "The version available at the ${VERSION} branch is ${TAG}"
    fi
    printf "We can install this version and the resulting installation "
    printf "would be located at ${VENVMAN_PYTHON_BUILDS_DIR}/${VERSION}\n"
    echo
    echo "To do this, we would run following:"
    echo
    echo "\$ cd ${VENVMAN_CPYTHON_REPO_DIR}" 
    echo "\$"
    echo "\$ if [ \$(git remote get-url origin) != ${VENVMAN_CPYTHON_REMOTE_URL} ]; then"
    echo "\$     return 1"
    echo "\$ fi"
    echo "\$"
    echo "\$ git checkout "$CHECKOUT""
    echo "\$ git reset --hard "$CHECKOUT""
    echo "\$"
    echo "\$ ./configure --prefix="${VENVMAN_PYTHON_BUILDS_DIR}/${VERSION}""
    echo "\$ make"
    echo "\$ make test"
    echo "\$ make install"
    echo
    printf "Would you like to continue with the install now? [Y/n]: "
    read -r response
    case "$response" in
        Y|y)
            ;;
        *)
            echo "Exiting the install."
            cd $MY_PWD
            return 1
            ;;
    esac

    ./configure --prefix="${VENVMAN_PYTHON_BUILDS_DIR}/${VERSION}" || return 1
    if [ $(command -v nproc &> /dev/null) ]; then
        echo "Running make -j$(nproc)"
        make -j$(nproc) || cd $MY_PWD && return 1

    elif [ $(command -v sysctl) ]; then
        ncpu=$(sysctl -n hw.ncpu)
        if [ -n "$ncpu" ]; then
            echo "Running make -j${ncpu}"
            make -j${ncpu} || cd $MY_PWD && return 1
        fi

    else
        make || cd $MY_PWD return 1
    fi
    
    if [ "$SKIP_TESTS" = "false" ]; then
        make test
    fi

    if ! make install; then
        echo "ERROR: make install failed" >&2
        echo "It is suggested to run"
        echo "    rm -rf ${VENVMAN_CPYTHON_REPO_DIR}"
        echo "    git clone ${VENVMAN_CPYTHON_REMOTE_URL} ${VENVMAN_CPYTHON_REPO_DIR}"
        echo "Then rerun the venvman make command."
        return 1
    fi

    if ! get_python_bin_path $VERSION > /dev/null; then
        echo "'make install' was successfull but the resulting binary for python ${VERSION} could not be found." >&2
        cd $MY_PWD
        return 1
    fi

    cd $MY_PWD
}


build_python_version_from_source "$@"
