#!/usr/bin/env bash


get_subversion_from_version() {
    ${VENVMAN_UTILS_DIR}/get_subversion_from_version $1 $2
}


get_python_bin_path() {
    VERSION=$1
    VERSION_MAJOR=$(get_subversion_from_version --major $VERSION)
    VERSION_MINOR=$(get_subversion_from_version --minor $VERSION)

    BINARY_PATH=$(which python${VERSION}) || BINARY_PATH=""
    if [ -n "$BINARY_PATH" ]; then
        echo $BINARY_PATH
        return 0
    fi

        
    if [ ! -d "${VENVMAN_PYTHON_BUILDS_DIR}/${VERSION}" ]; then
        return 1
    fi


    BINARY_PATHS=$(\
        find ${VENVMAN_PYTHON_BUILDS_DIR}/${VERSION} \
            -type f \
            -executable \
            -name "python${VERSION_MAJOR}.${VERSION_MINOR}" \
    )

    BINARY_PATH_FOUND=""
    for BINARY_PATH in $BINARY_PATHS; do
        BINARY_PATH_FOUND=$BINARY_PATH
        break
    done
    
    if [ -n "$BINARY_PATH_FOUND" ]; then
        echo $BINARY_PATH_FOUND
        return 0
    else
        return 1
    fi
}


get_python_bin_path "$1"
