#!/usr/bin/env bash


err_missing_option_value() {
    ${VENVMAN_UTILS_DIR}/messages/err_missing_option_value "$@"
}


err_invalid_option() {
    ${VENVMAN_UTILS_DIR}/messages/err_invalid_option "$@"
}


venvman_command_help_tag() {
    ${VENVMAN_UTILS_DIR}/messages/venvman_command_help_tag "$@"
}


venvman_delete() {(
    while [ "$#" -gt 0 ]; do
        case $1 in
            -n | --name)
                if [ -n "$2" ]; then
                    NAME="$2"
                    shift 2
                else
                    err_missing_option_value "delete" "--name"
                    return 1
                fi
                ;;
            -v | --version)
                if [ -n "$2" ]; then
                    VERSION="$2"
                    shift 2
                else
                    err_missing_option_value "delete" "--version"
                    return 1
                fi
                ;;
            -h | --help)
                venvman_command_help_tag "delete" \
                    --options \
                        "-n, --name <venv_name>" \
                        "-v, --version <python_version>" \
                        "-h, --help" \
                    --option-descriptions \
                        "Specify the name of the virtual environment to delete." \
                        "Specify the Python version associated with the virtual environment." \
                        "Display this help message." \
                    --examples \
                        "venvman delete -n myenv -v 3.10" \
                    --example-descriptions \
                        "Delete the virtual environment 'myenv' created with Python 3.10."
                return 0
                ;;
            *)
                err_invalid_option "delete" "$1"
                return 1
                ;;
        esac
    done
    
    VENV_PATH="${VENVMAN_ENVS_DIR}/${VERSION}/${NAME}"

    printf "The following enviornment is going to be deleted\n" 
    printf "${VENV_PATH}?\n" 
    printf "Do you want to continue [y/N]?: " 
    read -r response

    case "$response" in
        Y|y)
            rm -rf "$VENV_PATH"
            if [ ! -d "$VENV_PATH" ]; then
                echo "SUCCESS: Virtual environment $VENV_PATH has been deleted."
                return 0
            else
                echo "ERROR: $VENV_PATH has not been deleted."
                return 1
            fi
            ;;
        *)
            echo "Deletion cancelled."
            return 0
            ;;
    esac
)}


venvman_delete "$@"
