#!/usr/bin/env bash


err_missing_option_value() {
    ${VENVMAN_UTILS_DIR}/messages/err_missing_option_value "$@"
}


err_invalid_option() {
    ${VENVMAN_UTILS_DIR}/messages/err_invalid_option "$@"
}


venvman_command_help_tag() {
    ${VENVMAN_UTILS_DIR}/messages/venvman_command_help_tag "$@"
}


venvman_list() {
    while [ "$#" -gt 0 ]; do
        case $1 in
            -v | --version)
                if [ -n "$2" ]; then
                    VERSION="$2"
                    VENV_PATH="${VENVMAN_ENVS_DIR}/${VERSION}"
                    shift 2
                else
                    err_missing_option_value "list" "--version"
                    return 1
                fi
                ;;
            -h | --help)
                venvman_command_help_tag "list" \
                    --options \
                        "-v, --version <python_version>" \
                        "-h, --help" \
                    --option-descriptions \
                        "List virtual environments for a specific Python version." \
                        "Display this help message." \
                    --examples \
                        "venvman list -v 3.10" \
                    --example-descriptions \
                        "List virtual environments created with Python 3.10."
                shift
                return 0
                ;;
            *)
                err_invalid_option "list" "$1"
                return 1
                ;;
        esac
    done

    if [ -n "$VERSION" ]; then
        echo
        echo "Available virtual environments for Python ${VERSION}:"
        ls "$VENV_PATH" || return 1
        echo

    else
        echo
        for VERSION in $(find "$VENVMAN_ENVS_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort -t. -k1,1n -k2,2n); do
            echo "Available virtual environments for Python $VERSION:"
            ls "${VENVMAN_ENVS_DIR}/${VERSION}" || return 1
            echo
        done
    fi
}


venvman_list "$@"
