#!/usr/bin/env bash


get_subversion_from_version() {
    case $1 in
        --major)
            echo $(echo "$(echo "$2" | tr '.' ' ')" | awk "{print \$1}") 
            ;;
        --minor)
            echo $(echo "$(echo "$2" | tr '.' ' ')" | awk "{print \$2}") 
            ;;
        --patch)
            echo $(echo "$(echo "$2" | tr '.' ' ')" | awk "{print \$3}") 
            ;;
        *)
            return 1
            ;;
    esac
}


get_subversion_from_version "$@"
